import { Bot } from 'lucide-react';
const aiRules = {
    allowed: [
      'Brainstorming project ideas or names',
      'Debugging or improving small code snippets',
      'Fixing unfamiliar syntax',
    ],
    notAllowed: [
      'Submitting projects that are primarily or fully generated by AI',
      'Copy-pasting full codebases or solutions with minimal human contribution',
      'Using AI to bypass the learning process',
    ],
};

const AIPolicySection = () => {
  return (
    <section className="py-20 my-20 mb-10 bg-white">
        <div className="max-w-4xl mx-auto text-center ">
          <div className="inline-block mb-6 p-4 border-2 border-black rounded-full bg-white">
            <Bot className="w-10 h-10 text-black" />
          </div>
          <h3 className="font-paytone text-5xl md:text-6xl text-brand-charcoal mb-6">GENERATIVE AI POLICY</h3>
          <p className="font-outfit text-lg mb-10 text-gray-700 max-w-2xl mx-auto">
We fully encourage the use of generative Al (like ChatGPT, Copilot, etc.) in the completion of your project. However, to ensure a fair
competition          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-10 text-left">
            <div>
              <h4 className="font-bold text-xl text-green-600 mb-2">✅ Allowed Uses</h4>
              <ul className="list-disc list-inside space-y-2 font-outfit text-gray-800">
                {aiRules.allowed.map((item, idx) => (
                  <li key={idx}>{item}</li>
                ))}
              </ul>
            </div>
            <div>
              <h4 className="font-bold text-xl text-red-600 mb-2">❌ Not Allowed</h4>
              <ul className="list-disc list-inside space-y-2 font-outfit text-gray-800">
                {aiRules.notAllowed.map((item, idx) => (
                  <li key={idx}>{item}</li>
                ))}
              </ul>
            </div>
          </div>
        </div>
        </section>
          )
}

export default AIPolicySection